### ISSUE TITLE
Use ESLint

### ISSUE THREAD

**Issue by x-ji** [babe-project/babe-project#44]
ESLint is helpful for detecting errors. I ran it just now and it discovered a few problems (mostly about not prepending `var` when declaring a variable). I fixed those errors and added a `.eslintrc` file in 0b6f3cd62e2766fdc3227ccbcba357ded6dd8498. It could be helpful to have an ESLint plugin in the editor to check the JS files being edited.

**Comment by JannisBush** [comment]
Same as #34
