### ISSUE TITLE
SPR fails if you press another button

### ISSUE THREAD

**Issue by JannisBush** [babe-project/babe-project#59]
The spr views fail, if you press a key other than the space bar.

**Comment by JannisBush** [comment]
https://github.com/babe-project/babe-project/blob/master/src/babe-views.js#L1086

Apparently, this is the wanted behavior? 
I assume that a lot of people might accidentally press a key like `b` instead of the space bar every N trials (happened to me for example). Therefore we should change this behavior, because currently you are then stuck and can't do anything anymore.
But what do we want to do if a incorrect button was pressed?
- ignore
- restart the trial
- skip the trial and  record **FAILED** or something like that
- something else 
What is your opinion?

**Comment by x-ji** [comment]
That doesn't seem to make much sense. IMO the mispress should just be ignored?

**Comment by x-ji** [comment]
Though I'm not sure if there's something specific about the recorded data in such experiments.

**Comment by michael-franke** [comment]
Ignoring would be just fine.
